### ISSUE TITLE
Ascending and descending are reversed

### ISSUE THREAD

**Issue by joewiz** [line-o/xbow#1]
A very cool project! Congrats on the 1.0.0 release!

### Expected behavior

`(1 to 5) => xbow:ascending()` should return `1, 2, 3, 4, 5`

`(1 to 5) => xbow:descending()` should return `5, 4, 3, 2, 1`

### Actual behavior

`(1 to 5) => xbow:ascending()` returns `5, 4, 3, 2, 1`

`(1 to 5) => xbow:descending()` returns `1, 2, 3, 4, 5`

### Reproduction steps

See above.

### Please provide the following

*   Java Version: OpenJDK 13.3
*   exist-db version: 5.0.0
*   xbow version: 1.0.0
*   OS version: macOS 10.13.6

**Comment by line-o** [comment]
I tend to mix those up. Thanks for pointing that out, @joewiz !
